fix lineNumberStart on html parse
connectedcars/gettext-extractor pull request #59
Opened 2023-02-01 07:36 UTC by youthlin

First of all, thank you for this great project.

However, when using it (I use https://github.com/jshmrtn/vue3-gettext, which relies on this project to extract the translation messages from the .vue file), I found a small problem:

When the `lineNumberStart` option is passed to `HTMLParser` to parse, the option fails.

2023-02-01 21:16 UTC, lukasgeiter commented
Thanks for taking the time to create a PR! Could you elaborate a bit more on what exactly the problem is?

2023-02-02 02:40 UTC, youthlin commented
> Thanks for taking the time to create a PR! Could you elaborate a bit more on what exactly the problem is?

I'm sorry for not describing clearly.

see: https://github.com/jshmrtn/vue3-gettext/blob/0435499545a9c6d07dfffd7805dfd226f18fb413/scripts/extract.ts#L89-L101

```
import { parse } from "@vue/compiler-sfc";

...

  const htmlParser = extr.createHtmlParser([

   ...

    embeddedJsExtractor("*", jsParser), // Line 75
  ]);

...

if (fp.endsWith(".vue")) {
        const { descriptor, errors } = parse(buffer, { //  Line 90
          filename: fp,
          sourceRoot: process.cwd(),
        });

        ...

        if (descriptor.template) {  // Line 97
          htmlParser.parseString(descriptor.template.content, descriptor.filename, {
            lineNumberStart: descriptor.template.loc.start.line,  // Line 99
          });
        }

      ...

      }

...

```

When extract from vue file:
- First, in Line 90, it will use `@vue/compiler-sfc` to compile vue file and get the `descriptor`.
- Then,  extracting  from the `template` node, see Line 97.
- And, since the template node is not at the start of vue file, we should pass it's line number to htmlParser, see Line 99.

For the example below:

AboutView.vue
```vue
<script setup lang="ts">
import { ref } from 'vue';
const count = ref(0)
function add() {
  count.value++
}
</script>
<template>
  <div class="about">
    <h1>{{ $gettext("This is an about page") }}</h1>
    <p>{{ __('Hello, World') }}</p>
    <button @click="add">{{ _n("One Apple","%{count} Apples", count, { count: count+ '' }) }}</button>
  </div>
</template>

```

- When extract from the template node, in this case, the `lineNumberStart` passed to htmlParser is 8
- But, in `embeddedJsExtractor`, the lineNumberStart=8 not passed to jsParser. see https://github.com/lukasgeiter/gettext-extractor/blob/4390d5a5aba0878b665258c24c183c33d9ecbcfc/src/html/extractors/factories/embeddedJs.ts#L27
- So it will get the wrong number line

2023-02-06 02:21 UTC, youthlin commented
@lukasgeiter Hi, do you get my problem? Is this PR going to be accepted？

2023-02-06 22:01 UTC, lukasgeiter requested changes
Yes, I understand the problem now. Thanks for the detailed description. One little change and then this should be good to merge 👍

2023-02-06 22:01 UTC, lukasgeiter commented on src/html/extractors/factories/embeddedJs.ts
> +                lineNumberStart: lineNumberStart - 1
I think you should move the `- 1` up to line 27. It's needed to compensate for `element.sourceCodeLocation.startLine` being 1-based.

2023-02-07 18:12 UTC, lukasgeiter approved these changes

2023-02-07 18:13 UTC, merged

2023-02-07 18:35 UTC, lukasgeiter commented
Released with v3.6.2